# Generated by Django 5.0.3 on 2024-03-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensor_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
